name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Install and Build
        run: |
          rm -rf ./output ./build
          echo "@tailwind base; @tailwind components; @tailwind utilities;" > ./input.css
          npm install -g tailwindcss @tailwindcss/typography
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
          dart pub get
          dart run master.dart build &
          timeout=120
          while [ ! -f ./output/index.html ] && [ $timeout -gt 0 ]; do
            echo "Waiting for index.html... ($timeout seconds remaining)"
            sleep 5
            ((timeout-=5))
          done
          kill $(jobs -p) || true
          ls -R output
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build/output 
          publish_dir: ./output 
