name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tailwind
        run: npm install -D tailwindcss @tailwindcss/typography

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dart Dependencies
        run: dart pub get

      - name: Build Site
        run: |
          dart run master.dart --build & sleep 30 && kill $! || true 
          cp -r build/*.* build/output/ || true 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/output

      - name: Check Output
        run: ls -R && echo "The deployment completed successfully."
