name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tailwind
        run: npm install -D tailwindcss @tailwindcss/typography

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Get Dart Dependencies and Create Style Folder
        run: mkdir -p build/output/style && dart pub get

      - name: Build Site
        run: |
          npx tailwindcss init -p || true
          dart run master.dart build & sleep 120 && kill $(jobs -p) || true
          ls -R build/output

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/output
